<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cron Schedule Log' => '定时任务日志',
    'Date Created' => '创建时间',
    'Date Finished' => '完成时间',
    'ID' => 'ID',
    'Job Code' => '任务编码',
    'Messages' => '输出信息',
    'Select Status' => '请选择状态',
    'Status' => '状态',
    'Success' => '成功',
    'Error' => '出错',
    'Run' => '正在运行',
];
