<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cron Schedule Log' => '定時任務日誌',
    'Date Created' => '創建時間',
    'Date Finished' => '完成時間',
    'ID' => 'ID',
    'Job Code' => '任務編碼',
    'Messages' => '輸出信息',
    'Select Status' => '請選擇狀態',
    'Status' => '狀態',
    'Success' => '成功',
    'Error' => '出錯',
    'Run' => '正在運行',
];
